language: cpp
sudo: false

# Build matrix:
compiler:
- gcc
- clang
env:
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=0
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30 PYTHON_INTERP=python2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - bison
    - flex
    - libavcodec-dev
    - libavformat-dev
    - libavresample-dev
    - libavutil-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libswscale-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - python-virtualenv
    - zlib1g-dev
    - fakeroot

before_install:
# clean up remnants of makepanda
- mv makepanda/test_imports.py .
- makepanda/selfdestruct.py --yes

install:
- virtualenv --python=${PYTHON_INTERP:-python3.4} venv && source venv/bin/activate
- pip install pytest

before_script:
- mkdir built
- cd built

script:
- cmake -DHAVE_GTK2=NO -DBUILD_METALIBS=$BUILD_METALIBS -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT .. 
- make -j4

- export PYTHONPATH=$PWD
- python ../test_imports.py
- pytest ../tests

notifications:
  irc:
    channels:
    - "chat.freenode.net#panda3d"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
