language: cpp
sudo: false
matrix:
  include:
    - compiler: clang
      env: PYTHONV=python3 FLAGS=--installer
    - compiler: clang
      env: PYTHONV=python2.7 FLAGS=--override=STDFLOAT_DOUBLE=1
    - compiler: gcc
      env: PYTHONV=python2.7 FLAGS=--optimize=4
      before_install:
        - export CC=gcc-4.7
        - export CXX=g++-4.7
    - compiler: clang
      env: PYTHONV=python3 FLAGS=--no-python SKIP_TESTS=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - bison
    - flex
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - python-virtualenv
    - zlib1g-dev
    - fakeroot
install:
    - virtualenv --python=$PYTHONV venv && source venv/bin/activate
    - $PYTHONV -m pip install pytest
script:
    - $PYTHONV makepanda/makepanda.py --everything --git-commit $TRAVIS_COMMIT $FLAGS --threads 4
    - test -n "$SKIP_TESTS" || LD_LIBRARY_PATH=built/lib PYTHONPATH=built $PYTHONV -m pytest -v tests
notifications:
  irc:
    channels:
      - secure: "jfwHT9RHAVOGRGTMY8TpYKJI6rq8nFoIj41Y0soZdJQNWtSSFEK9AyzZeMY+2dHga7cR/X+/0NWZ2ehhedTnd9FvlzOnMWWC3K0I/b3XWbEdVEqIZnggFkKGqs82Gy3omguRC63yWupeJCcSCckIhoWbLzWy6xV8lF5WC80iXi8="
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: false
  webhooks:
    urls:
      - https://www.panda3d.org/webhooks/travis-ci.php
    on_success: change
    on_failure: always
