language: cpp
sudo: false

# Build matrix:
os:
- linux
- osx
compiler:
- clang
env:
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30 PYTHON_INTERP=python2.7
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0
matrix:
  exclude:
    - os: osx
      env: BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0
  include:
    - os: osx
      env: BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30 COMPOSITE_SOURCE_EXCLUSIONS=p3showbase;p3dtoolutil;p3cocoadisplay;p3osxdisplay;p3tinydisplay;p3display
    - compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - bison
    - flex
    - libavcodec-dev
    - libavformat-dev
    - libavresample-dev
    - libavutil-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libswscale-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - python3-pip
    - python-virtualenv
    - zlib1g-dev
    - fakeroot

before_install:
# clean up remnants of makepanda
- mv makepanda/test_imports.py .
- makepanda/selfdestruct.py --yes

install:
- >
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install python@3 eigen libtar fftw libsquish zlib ffmpeg freetype \
    bullet opencv assimp libvorbis openssl || true
    brew install ode --with-shared

    # We can't trust brew to make the right symlinks, so execute commands as modules
    ${PYTHON_INTERP:-python3} -m pip install virtualenv
    ${PYTHON_INTERP:-python3} -m virtualenv venv
  else
    virtualenv --python=${PYTHON_INTERP:-python3} venv
  fi
- source venv/bin/activate
- pip install pytest

before_script:
- mkdir built
- cd built

script:
# This is kind of a hack, but needed to test non-metalib builds (until
# interrogate has a way of explicitly calling init_libpanda)
- '[ "x$BUILD_METALIBS" == "xON" ] || export LDFLAGS=-Wl,--no-as-needed'

- >
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    if [[ "$PYTHON_INTERP" == "python2.7" ]]; then
      export PY2_CMAKE_ARGS=-DPYTHON_EXECUTABLE=/usr/local/Frameworks/Python.framework/Versions/2.7/bin/python
    fi

    cmake -DBUILD_METALIBS=$BUILD_METALIBS \
    -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT \
    -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl $PY2_CMAKE_ARGS ..
  else
    cmake -DHAVE_GTK2=NO -DBUILD_METALIBS=$BUILD_METALIBS \
    -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT ..
  fi
- make -j4

- export PYTHONPATH=$PWD
- python ../test_imports.py
- pytest -v ../tests

notifications:
  irc:
    channels:
    - "chat.freenode.net#panda3d"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: false
